version: 1.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - dev
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
environment:
  CODECOV_TOKEN: 93f1ba74-2bc4-4b01-8e9e-3a3c97825e91
build_script:
- ps: "dotnet pack src/AspNetCore.AutoHealthCheck.sln -o ./artefacts/"
test_script:
- ps: "dotnet test src/AspNetCore.AutoHealthCheck.sln"
artifacts:
- path: ./artefacts/*.nupkg
  name: NuGet
